import type { Locale } from "@/i18n/config";
import { Badge } from "@/components/ui/badge";

type Row = {
  name: string;
  what: Record<Locale, string>;
};

const formations: Row[] = [
  {
    name: "ring · grid · sphere · spiral · line · heart · star",
    what: {
      de: "7 prozedurale Generatoren: Parameter-getrieben, direkt aus dem Inspector editierbar.",
      en: "7 procedural generators: parameter-driven, editable straight from the inspector.",
    },
  },
  {
    name: "firework-burst · apple-tree-shake · breathing-sphere",
    what: {
      de: "3 animierte Formationen mit eigenem internem Timing.",
      en: "3 animated formations with their own internal timing.",
    },
  },
  {
    name: "create_formation_from_text",
    what: {
      de: "Frei-Text zu Punktwolke, generiert vom KI-Agenten direkt im Graphen.",
      en: "Free text to point cloud, generated by the AI agent straight into the graph.",
    },
  },
];

const transitions: Row[] = [
  {
    name: "stagger · spiral · explosion · implosion · cascade · morph · color-sweep · bounce",
    what: {
      de: "8 Strategien. Jede besitzt ihr eigenes Point-Mapping und einen Minimum-Dauer-Schätzer; Timing und Drohnen-Allokation gehören aber nicht dazu (siehe Architektur-Gesetz Nr. 3).",
      en: "8 strategies. Each owns its own point mapping and minimum-duration estimator, but not timing or drone allocation (see architectural law no. 3).",
    },
  },
];

const idleBehaviors: Row[] = [
  {
    name: "hover · orbit · breathe · random-walk · figure-8 · swarm · sparkle · pulse · wave · spin · drift",
    what: {
      de: "11 Idle-Verhalten für Drohnen, die an Formation-Knoten attached sind, mit per-Achse-Inheritance-Flags.",
      en: "11 idle behaviors for drones attached to formation nodes, with per-axis inheritance flags.",
    },
  },
];

const colorPrograms: Row[] = [
  {
    name: "solid · gradient · rainbow · pulse · chase (10 Programme)",
    what: {
      de: "10 Farbprogramme: Konstanten, Gradients, Regenbogen, Pulse, Chase-Pattern.",
      en: "10 color programs: solids, gradients, rainbows, pulses, chase patterns.",
    },
  },
];

const projectShape: Record<Locale, Array<{ k: string; v: string }>> = {
  de: [
    { k: "Quelldateien (ohne Tests)", v: "110" },
    { k: "Quell-LOC (ohne Tests)", v: "~22.700" },
    { k: "Testdateien", v: "41" },
    { k: "Test-LOC", v: "~7.900" },
    { k: "Registrierte KI-Tools", v: "30+" },
    { k: "Transition-Strategien", v: "8" },
    { k: "Idle-Verhalten", v: "11" },
    { k: "Formation-Generatoren", v: "7 + 3 animiert" },
  ],
  en: [
    { k: "Source files (excl. tests)", v: "110" },
    { k: "Source LOC (excl. tests)", v: "~22,700" },
    { k: "Test files", v: "41" },
    { k: "Test LOC", v: "~7,900" },
    { k: "Registered AI tools", v: "30+" },
    { k: "Transition strategies", v: "8" },
    { k: "Idle behaviors", v: "11" },
    { k: "Formation generators", v: "7 + 3 animated" },
  ],
};

const architecturalLaws: Record<Locale, string[]> = {
  de: [
    "ShowGraph ist kanonisch. Alles andere ist eine abgeleitete Sicht.",
    "Live-Preview darf approximieren; Bake nicht.",
    "Transitionen besitzen Point-Mapping, Entry/Exit und Motion-Interpolation, aber niemals Timing oder Drohnen-Allokation.",
    "Registries sind die einzige Erweiterungs-Oberfläche. Eine neue Transition, ein Generator, ein Farbprogramm ist ein einzelner register…()-Aufruf.",
  ],
  en: [
    "ShowGraph is canonical. Everything else is a derived view.",
    "Live preview is allowed to approximate; bake is not.",
    "Transitions own point mapping, entry/exit and motion interpolation, never timing or drone allocation.",
    "Registries are the only extension surface. Adding a transition, generator or color program is a single register…() call.",
  ],
};

const decisions: Record<Locale, { title: string; body: string }[]> = {
  de: [
    {
      title: "Graph als Single Source of Truth",
      body: "Ein einziges typisiertes Modell ist die kanonische Zustandsquelle: launch / formation / transition / idle / land plus flow- und attachment-Kanten. React-Flow-Canvas, Three.js-Viewport, Inspector-Panels, Validator und Exporter sind allesamt abgeleitete Sichten. Kein doppelter State, keine Drift.",
    },
    {
      title: "Preview vs. Bake - zwei klare Pfade",
      body: "evaluateAtTime() läuft im Main-Thread, unter 16ms pro Frame für 60-fps-Scrubbing, mit zugelassenen Approximationen wie linearer Interpolation und nicht durchgesetzten Geschwindigkeits-Constraints. bakeShow() läuft in einem Web-Worker mit voller Physik-Enforcement und ist als einziges berechtigt, Export-Trajektorien zu produzieren. Der Vertrag zwischen beiden ist explizit und getestet.",
    },
    {
      title: "KI-Agent als vollwertiger Editor",
      body: "Ein Claude-Tool-Calling-Agent hat Zugriff auf 30+ typisierte Tools: create_formation_from_text, add_transition_node, set_color_program, generate_music_synced_show, analyze_image_for_formation, fix_all_violations. Jedes Write-Tool schreibt vorher einen History-Snapshot; jede KI-Änderung lässt sich mit Ctrl+Z rückgängig machen.",
    },
    {
      title: "Registries als einzige Erweiterungs-Oberfläche",
      body: "Eine neue Transition, ein Formation-Generator, ein Farbprogramm: ein einziger register…()-Call. Das macht das System für mich selbst und für KI-Tooling gleichermaßen erweiterbar. Die Engine kennt nur Strategien, nicht die spezifischen Implementierungen.",
    },
    {
      title: "Physik-Validierung getrennt vom Editor",
      body: "Per-Segment-Geschwindigkeit (horizontal + vertikal), Beschleunigung, Drohnen-Paar-Abstand, Höhen-Floor und Geofence werden gegen das gebakte Resultat geprüft. Auto-Fix-Patches existieren für die häufigen Verstöße; Auto-Timing weist Dauern so zu, dass Constraints erfüllt sind.",
    },
    {
      title: "Crash-Recovery via IndexedDB",
      body: "Autosave landet in IndexedDB. Reload nach einem Crash bietet an, die zuletzt in Bearbeitung befindliche Show wiederherzustellen: kein verlorener Stand bei Browser-Crash oder versehentlich geschlossenem Tab.",
    },
  ],
  en: [
    {
      title: "Graph as single source of truth",
      body: "One typed model is the canonical state: launch / formation / transition / idle / land plus flow and attachment edges. The React Flow canvas, Three.js viewport, inspector panels, validator and exporter are all derived views. No duplicated state, no drift.",
    },
    {
      title: "Preview vs. bake - two clear paths",
      body: "evaluateAtTime() runs on the main thread, sub-16ms per frame for 60 fps scrubbing, with permitted approximations like linear interpolation and unenforced velocity constraints. bakeShow() runs in a Web Worker with full physics enforcement and is the only thing allowed to produce export trajectories. The contract between the two is explicit and tested.",
    },
    {
      title: "AI agent as a first-class editor",
      body: "A Claude tool-calling agent has access to 30+ typed tools: create_formation_from_text, add_transition_node, set_color_program, generate_music_synced_show, analyze_image_for_formation, fix_all_violations. Every write tool snapshots history first, so any AI change is undoable with Ctrl+Z.",
    },
    {
      title: "Registries as the only extension surface",
      body: "A new transition, a formation generator, a color program: one register…() call. That keeps the system equally extensible by me and by AI tooling. The engine only knows about strategies, not their specific implementations.",
    },
    {
      title: "Physics validation separated from the editor",
      body: "Per-segment velocity (horizontal + vertical), acceleration, drone-pair spacing, altitude floor and geofence are validated against the baked result. Auto-fix patches exist for the common violations; auto-timing assigns durations to satisfy constraints.",
    },
    {
      title: "Crash recovery via IndexedDB",
      body: "Autosave lands in IndexedDB. After a reload-following-crash, the editor offers to restore the most recent in-progress show: no lost state from a browser crash or accidental tab close.",
    },
  ],
};

const wipNotes: Record<Locale, { title: string; status: string; body: string }[]> = {
  de: [
    {
      title: "Was steht",
      status: "stable",
      body: "Graph-Engine, Preview-Pfad, deterministisches Bake im Worker, 8 Transitions / 11 Idles / 10 Color-Programme, IndexedDB-Autosave, CSV-Export. 41 Testdateien decken die harten Teile ab: Topology, Timing, Round-Trip-Serialisierung, Split/Merge-Flow.",
    },
    {
      title: "Was in Arbeit ist",
      status: "in arbeit",
      body: "KI-Agent ist live aber neue Tools landen laufend; Music-Sync-Pipeline wird noch ausgebaut; MP4-Render-Export ist optional und nicht produktionsfest. Standalone-Companion ist ein eigener kleiner App-Slot, der noch nicht voll mit dem Haupt-Editor verheiratet ist.",
    },
    {
      title: "Was bewusst draußen ist",
      status: "non-goals",
      body: "Multi-User-Collaboration, Cloud-Storage, eigenes Hardware-Protokoll. Der Editor ist single-user, browser-first, exportiert in offene Formate (CSV-Waypoints + JSON-Projekt). Das soll auch so bleiben.",
    },
  ],
  en: [
    {
      title: "What stands",
      status: "stable",
      body: "Graph engine, preview path, deterministic bake in a worker, 8 transitions / 11 idles / 10 color programs, IndexedDB autosave, CSV export. 41 test files cover the hard parts: topology, timing, round-trip serialization, split/merge flow.",
    },
    {
      title: "What's in flight",
      status: "in progress",
      body: "AI agent is live but new tools keep landing; the music-sync pipeline is still expanding; the MP4 render export is optional and not production-grade yet. The standalone companion is its own small app slot, not yet fully wedded to the main editor.",
    },
    {
      title: "What is intentionally out",
      status: "non-goals",
      body: "Multi-user collaboration, cloud storage, a proprietary hardware protocol. The editor is single-user, browser-first, and exports to open formats (CSV waypoints + JSON project). That is staying that way.",
    },
  ],
};

const labels = {
  de: {
    wipBanner:
      "Aktiv in Entwicklung. Das Live-Deployment auf drones.prototyp.ms läuft, der Kern (Graph-Engine, Preview, Bake, KI-Agent) steht. Neue Tools, Music-Sync und Feinschliff landen laufend.",
    architectureTitle: "Architektur-Gesetze",
    architectureLead:
      "Vier Regeln, die im Code (und in Tests) durchgesetzt werden. Sie machen den Editor erweiterbar, ohne den Kern aufzuweichen.",
    librariesTitle: "Im Editor enthalten",
    librariesLead:
      "Die Bibliotheken hinter den Knoten. Alles registrierbar, alles vom KI-Agenten erreichbar.",
    formationsLabel: "Formation-Generatoren",
    transitionsLabel: "Transition-Strategien",
    idlesLabel: "Idle-Verhalten",
    colorsLabel: "Farbprogramme",
    detailCol: "Beschreibung",
    decisionsTitle: "Schlüsselentscheidungen",
    statsTitle: "Projekt-Größe (Stand jetzt)",
    statsLead:
      "Eckdaten aus dem aktuellen Stand. Test-LOC wird nicht zur 'Größe' gezählt, ist aber relevant für die Qualität der harten Teile.",
    statCol: "Kennzahl",
    valueCol: "Wert",
    statusTitle: "Status - was steht, was in Arbeit ist",
    deploymentTitle: "Deployment",
    deploymentBody:
      "Statisches Vite-Build, ausgeliefert über nginx auf der gleichen VPS wie meine anderen .prototyp.ms-Apps. Keine Server-Komponente: alle KI-Aufrufe laufen mit einem benutzer-bereitgestellten Claude-API-Key direkt aus dem Browser. Ohne Key arbeitet der Editor vollständig; nur das Chat-Panel ist dann deaktiviert.",
  },
  en: {
    wipBanner:
      "Actively developed. The live deployment at drones.prototyp.ms is running, the core (graph engine, preview, bake, AI agent) is solid. New tools, music sync and polish keep landing.",
    architectureTitle: "Architectural laws",
    architectureLead:
      "Four rules enforced in code (and in tests). They keep the editor extensible without softening the core.",
    librariesTitle: "What's in the editor",
    librariesLead:
      "The libraries behind the nodes. Everything registrable, everything reachable by the AI agent.",
    formationsLabel: "Formation generators",
    transitionsLabel: "Transition strategies",
    idlesLabel: "Idle behaviors",
    colorsLabel: "Color programs",
    detailCol: "Description",
    decisionsTitle: "Key engineering decisions",
    statsTitle: "Project shape (as of now)",
    statsLead:
      "Stats from the current state. Test LOC isn't counted as 'size', but it's relevant for the quality of the hard parts.",
    statCol: "Metric",
    valueCol: "Value",
    statusTitle: "Status - what stands, what's in flight",
    deploymentTitle: "Deployment",
    deploymentBody:
      "Static Vite build served by nginx on the same VPS as my other .prototyp.ms apps. No server component: every AI call runs with a user-supplied Claude API key directly from the browser. Without a key the editor works fully; only the chat panel is disabled.",
  },
};

export function DronesContent({ locale }: { locale: Locale }) {
  const l = labels[locale];

  return (
    <div className="space-y-20">
      <div className="flex gap-4 rounded-2xl border border-[var(--color-accent)]/40 bg-[var(--color-accent)]/10 p-5">
        <div className="mt-0.5 flex h-2.5 w-2.5 shrink-0 animate-pulse rounded-full bg-[var(--color-accent)]" />
        <p className="text-sm leading-relaxed">{l.wipBanner}</p>
      </div>

      <Section title={l.statusTitle}>
        <div className="grid gap-4 md:grid-cols-3">
          {wipNotes[locale].map((n) => (
            <div
              key={n.title}
              className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"
            >
              <div className="flex items-center justify-between gap-2">
                <h3 className="text-sm font-semibold tracking-tight">{n.title}</h3>
                <Badge>{n.status}</Badge>
              </div>
              <p className="mt-2 text-sm leading-relaxed text-[var(--color-muted-foreground)]">
                {n.body}
              </p>
            </div>
          ))}
        </div>
      </Section>

      <Section title={l.decisionsTitle}>
        <div className="grid gap-4 md:grid-cols-2">
          {decisions[locale].map((item) => (
            <NoteCard key={item.title} title={item.title} body={item.body} />
          ))}
        </div>
      </Section>

      <Section title={l.architectureTitle} lead={l.architectureLead}>
        <ol className="space-y-3">
          {architecturalLaws[locale].map((law, idx) => (
            <li
              key={idx}
              className="flex gap-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-4"
            >
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[var(--color-accent)] text-xs font-semibold text-[var(--color-accent-foreground)]">
                {idx + 1}
              </span>
              <p className="text-sm leading-relaxed">{law}</p>
            </li>
          ))}
        </ol>
      </Section>

      <Section title={l.librariesTitle} lead={l.librariesLead}>
        <div className="space-y-8">
          <LibraryGroup label={l.formationsLabel} rows={formations} locale={locale} />
          <LibraryGroup label={l.transitionsLabel} rows={transitions} locale={locale} />
          <LibraryGroup label={l.idlesLabel} rows={idleBehaviors} locale={locale} />
          <LibraryGroup label={l.colorsLabel} rows={colorPrograms} locale={locale} />
        </div>
      </Section>

      <Section title={l.statsTitle} lead={l.statsLead}>
        <div className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)]">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[var(--color-border)] bg-[var(--color-muted)]/40 text-left">
                <Th>{l.statCol}</Th>
                <Th>{l.valueCol}</Th>
              </tr>
            </thead>
            <tbody>
              {projectShape[locale].map((row) => (
                <tr
                  key={row.k}
                  className="border-b border-[var(--color-border)] last:border-b-0"
                >
                  <Td className="text-[var(--color-muted-foreground)]">{row.k}</Td>
                  <Td className="font-mono">{row.v}</Td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title={l.deploymentTitle}>
        <p className="text-sm leading-relaxed text-[var(--color-muted-foreground)]">
          {l.deploymentBody}
        </p>
      </Section>
    </div>
  );
}

function LibraryGroup({
  label,
  rows,
  locale,
}: {
  label: string;
  rows: Row[];
  locale: Locale;
}) {
  return (
    <div>
      <p className="text-xs uppercase tracking-widest text-[var(--color-muted-foreground)]">
        {label}
      </p>
      <div className="mt-3 space-y-2">
        {rows.map((row) => (
          <div
            key={row.name}
            className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-4"
          >
            <p className="font-mono text-xs text-[var(--color-foreground)]">
              {row.name}
            </p>
            <p className="mt-1.5 text-sm text-[var(--color-muted-foreground)]">
              {row.what[locale]}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function Section({
  title,
  lead,
  children,
}: {
  title: string;
  lead?: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-xs font-semibold uppercase tracking-widest text-[var(--color-accent)]">
        {title}
      </h2>
      {lead && (
        <p className="mt-3 max-w-2xl text-base text-[var(--color-muted-foreground)]">
          {lead}
        </p>
      )}
      <div className="mt-6">{children}</div>
    </section>
  );
}

function Th({ children }: { children: React.ReactNode }) {
  return (
    <th className="px-4 py-3 text-xs font-semibold uppercase tracking-widest text-[var(--color-muted-foreground)]">
      {children}
    </th>
  );
}

function Td({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <td className={`px-4 py-3 align-top ${className ?? ""}`}>{children}</td>
  );
}

function NoteCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
      <h3 className="text-sm font-semibold tracking-tight">{title}</h3>
      <p className="mt-2 text-sm leading-relaxed text-[var(--color-muted-foreground)]">
        {body}
      </p>
    </div>
  );
}
